# Generated by Django 5.2.8 on 2025-11-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
