# Generated by Django 5.2.8 on 2025-11-28 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0006_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('ISBN', models.CharField(max_length=50, unique=True)),
                ('Pages', models.IntegerField()),
                ('Status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=50)),
                ('Genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('biography', 'Biography'), ('self-help', 'Self-Help'), ('children', 'Children'), ('young adult', 'Young Adult'), ('young adult', 'Young Adult'), ('young adult', 'Young Adult'), ('young adult', 'Young Adult')], max_length=50)),
                ('Added_on', models.DateTimeField(auto_now_add=True)),
                ('Updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('is_returned', models.BooleanField(default=False)),
                ('fine', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.users')),
            ],
        ),
    ]
