# Generated by Django 5.2.8 on 2025-11-28 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_rename_members_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Published_date',
            field=models.DateField(default=datetime.date(2025, 11, 28)),
        ),
        migrations.AlterField(
            model_name='book',
            name='Genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('biography', 'Biography'), ('selfhelp', 'Self-Help'), ('children', 'Children'), ('youngadult', 'Young Adult'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('history', 'History')], max_length=50),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 11, 28)),
        ),
    ]
