# Generated by Django 5.2.8 on 2025-11-29 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0010_book_published_date_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Published_date',
            field=models.DateField(default=datetime.date(2025, 11, 29)),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 11, 29)),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(default='MBR-', max_length=50),
        ),
    ]
