# Generated by Django 5.2.8 on 2025-11-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0011_alter_book_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(default='STF-', max_length=50),
        ),
    ]
