# Generated by Django 5.2.8 on 2025-11-29 10:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Published_date', models.DateField(default=datetime.date(2025, 11, 29))),
                ('Image', models.ImageField(upload_to='images/')),
                ('ISBN', models.CharField(max_length=50, unique=True)),
                ('Pages', models.IntegerField()),
                ('Status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=50)),
                ('Genre', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('biography', 'Biography'), ('selfhelp', 'Self-Help'), ('children', 'Children'), ('youngadult', 'Young Adult'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('history', 'History')], max_length=50)),
                ('Added_on', models.DateTimeField(auto_now_add=True)),
                ('Updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('member_id', models.CharField(default='MBR-', max_length=50)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(default=datetime.date(2026, 11, 29))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('is_returned', models.BooleanField(default=False)),
                ('fine', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_management.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_management.member')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('employee_id', models.CharField(default='STF-', max_length=50)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('role', models.CharField(choices=[('Librarian', 'Librarian'), ('Assistant Librarian', 'Assistant Librarian'), ('Library Admin', 'Library Admin')], default='Librarian', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
