# Generated by Django 5.2.8 on 2025-11-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
