# Generated by Django 5.2.8 on 2025-12-06 19:45

import datetime
import library_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0002_borrowrecord_is_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Blocked', 'Blocked')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='Published_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='member',
            name='expiry_date',
            field=models.DateField(default=library_management.models.get_expiry_date),
        ),
    ]
