# Generated by Django 5.2.8 on 2025-12-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0003_member_status_alter_book_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
