# Generated by Django 5.2.8 on 2025-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0004_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_login',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_login',
            field=models.DateField(null=True),
        ),
    ]
