# Generated by Django 5.2.8 on 2025-12-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0005_member_last_login_staff_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_login',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_login',
            field=models.TimeField(null=True),
        ),
    ]
