# Generated by Django 5.2.8 on 2025-12-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0006_alter_member_last_login_alter_staff_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
