# Generated by Django 5.2.8 on 2025-12-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0008_alter_staff_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='last_login',
            field=models.CharField(blank=True, null=True),
        ),
    ]
