# Generated by Django 5.2.8 on 2025-12-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0010_remove_member_last_login_remove_staff_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
