# Generated by Django 5.2.8 on 2025-12-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0012_alter_member_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='login_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
