# Generated by Django 5.2.8 on 2025-12-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0013_staff_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
