# Generated by Django 5.2.8 on 2025-12-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0014_alter_staff_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
