# Generated by Django 5.2.8 on 2025-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0015_member_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
