# Generated by Django 5.2.8 on 2025-12-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0016_staff_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AddField(
            model_name='staff',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
