# Generated by Django 5.2.8 on 2025-12-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0017_remove_member_status_staff_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='borrow_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
