# Generated by Django 5.2.8 on 2025-12-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0018_staff_borrow_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='borrow_count',
        ),
        migrations.AddField(
            model_name='member',
            name='borrow_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
