# Generated by Django 5.2.8 on 2025-12-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0019_remove_staff_borrow_count_member_borrow_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='borrow_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
