# Generated by Django 5.2.8 on 2025-12-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0020_borrowrecord_borrow_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_id',
            new_name='lib_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='employee_id',
            new_name='lib_id',
        ),
    ]
